### ISSUE TITLE
Update Site not work with Eclipse Neon

### ISSUE THREAD

**Issue by IT-Berater** [DevBoost/JaMoPP#32]
Hi,

the update site not work with Eclipse Neon Version.

I generate this: [http://wenzlaff.de/mindmaps.html](url)

Best regards

Thomas

**Comment by mirkoseifert** [comment]
I've fixed the broken links to associated update sites. However, my Eclipse doesn't pick up these changes, probably due to some caching.

As a temporary workaround you can add 'http://update.emftext.org/trunk/' as update site to your Eclipse installation and the try to install JaMoPP again. This works for me with Eclipse Neon.2.

**Comment by IT-Berater** [comment]
Hi Mirko,

thanks for the workaround. Update works :-) 

I add the *.jars manuel to the classpath.

Result on http://wenzlaff.de/mindmaps-2016.html 

One Error is on a **manifest.mf** File: 

on Description	Resource	Path	Location	Type
Bundle 'de.devboost.commenttemplate' cannot be resolved	MANIFEST.MF	/TWTextGenerator/META-INF	line 6	Plug-in Problem

the manifest.mf:

> Manifest-Version: 1.0
> Bundle-ManifestVersion: 2
> Bundle-Name: TestCommentTemplate
> Bundle-SymbolicName: TWTextGenerator
> Bundle-Version: 1.0.0.qualifier
> Require-Bundle: de.devboost.commenttemplate;bundle-version="0.9.2"
> Bundle-RequiredExecutionEnvironment: JavaSE-1.6

How can i set the projekt later as plugin-projekt typ?
